import type { FieldSpec, SaveMap } from "./types";

function field(
  partial: Omit<FieldSpec, "stride"> & { stride?: number },
): FieldSpec {
  return {
    stride: partial.size === 2 ? 2 : 1,
    min: 0,
    max: partial.size === 2 ? 65535 : 255,
    ...partial,
  };
}

const I2_SRC =
  "DLH.NET cheat (Marc Rene Delhalle); cross-checked with ppa.pl Amiga table (offsets similar, not identical). Unconfirmed until a real DOS .SAV is imported.";

const I2_NEXT =
  "Import a real Ishar-2 .SAV, change one in-game value, save, and binary-diff. Repeat per field.";

export const ISHAR2_CLASSES = [
  { id: 0x00, name: "Knappe", nameEn: "Squire" },
  { id: 0x01, name: "Krieger", nameEn: "Warrior" },
  { id: 0x02, name: "Waldläufer", nameEn: "Ranger" },
  { id: 0x03, name: "Barbar", nameEn: "Barbarian" },
  { id: 0x04, name: "Dieb", nameEn: "Thief" },
  { id: 0x05, name: "Geistlicher", nameEn: "Cleric" },
  { id: 0x06, name: "Magier", nameEn: "Mage" },
  { id: 0x07, name: "Bogenschütze", nameEn: "Archer" },
  { id: 0x08, name: "Spion", nameEn: "Spy" },
  { id: 0x09, name: "Priester", nameEn: "Priest" },
  { id: 0x0a, name: "Söldner", nameEn: "Mercenary" },
  { id: 0x0b, name: "Bettler", nameEn: "Beggar" },
  { id: 0x0c, name: "Mörder", nameEn: "Assassin" },
  { id: 0x0d, name: "Priesterin", nameEn: "Priestess" },
  { id: 0x0e, name: "Hypnotiseur", nameEn: "Hypnotist" },
  { id: 0x0f, name: "Hypnotiseur", nameEn: "Hypnotist (alt)" },
  { id: 0x10, name: "Hexe", nameEn: "Witch" },
  { id: 0x11, name: "Schwarzer Ritter", nameEn: "Black Knight" },
  { id: 0x12, name: "Okkulter Mönch", nameEn: "Occult Monk" },
  { id: 0x13, name: "Druide", nameEn: "Druid" },
];

export const ISHAR2_RACES = [
  { id: 0x01, name: "Mensch", nameEn: "Human" },
  { id: 0x02, name: "Elf", nameEn: "Elf" },
  { id: 0x03, name: "Zwerg", nameEn: "Dwarf" },
  { id: 0x04, name: "Ork", nameEn: "Orc" },
  { id: 0x05, name: "Echsenmensch", nameEn: "Lizardman" },
];

/** Decimal offsets from the public Ishar 2 hex-cheat table. */
export const ISHAR2_SAVE: SaveMap = {
  id: "ishar2-sav-dlh",
  game: "ishar2",
  title: "Ishar 2 Savegame (DOS, public cheat map)",
  partySize: 5,
  minLength: 7734,
  defaultEndian: "be",
  confidence: "probable",
  notes:
    "Party stats are stored as arrays of 5, not as per-character records. 16-bit fields may be big-endian (Amiga heritage). Endian is a toggle until proven.",
  classes: ISHAR2_CLASSES,
  races: ISHAR2_RACES,
  fields: {
    xp: field({
      id: "xp",
      label: "Erfahrung",
      labelEn: "Experience",
      offset: 986,
      size: 2,
      unit: "u16",
      confidence: "probable",
      tooltip:
        "Erfahrungspunkte. In Ishar steigen Werte nicht nur über Level, sondern über Training und Nutzung. Formel Level-up: unbekannt.",
      evidence: {
        kind: "suspected",
        summary: "10 Bytes ab Offset 986, 2 Bytes je Charakter.",
        source: I2_SRC,
        nextTest: I2_NEXT,
      },
    }),
    hp: field({
      id: "hp",
      label: "Vitalität",
      labelEn: "Hit points",
      offset: 996,
      size: 2,
      unit: "u16",
      confidence: "probable",
      tooltip:
        "Aktuelle Lebenspunkte / Vitalität. Rast, Nahrung und Heilzauber füllen sie auf. Obergrenze unbekannt (Cheat-Autoren warnten vor Werten >255 in Ishar 1).",
      evidence: {
        kind: "suspected",
        summary: "2 Bytes je Charakter ab 996.",
        source: I2_SRC,
        nextTest: I2_NEXT,
      },
    }),
    hpMax: field({
      id: "hpMax",
      label: "Vitalität max.",
      labelEn: "Max hit points",
      offset: 1016,
      size: 2,
      unit: "u16",
      confidence: "probable",
      tooltip: "Maximale Vitalität. Wachstum pro Level: unbekannt.",
      evidence: {
        kind: "suspected",
        summary: "2 Bytes je Charakter ab 1016.",
        source: I2_SRC,
        nextTest: I2_NEXT,
      },
    }),
    gold: field({
      id: "gold",
      label: "Gold",
      labelEn: "Gold",
      offset: 1026,
      size: 2,
      unit: "u16",
      confidence: "probable",
      tooltip:
        "Mitgeführtes Gold pro Charakter. Ishar 1 verlangt Gold zum Speichern; Ishar 2 nicht. Eine zweite Gold-Stelle im File wurde von IshadNha vermutet.",
      evidence: {
        kind: "suspected",
        summary: "2 Bytes je Charakter ab 1026. Zweite Kopie möglich.",
        source: I2_SRC + " / GOG-Forum IshadNha",
        nextTest: "Gold geben, speichern, alle 16-bit-Treffer des Betrags listen.",
      },
    }),
    classId: field({
      id: "classId",
      label: "Beruf",
      labelEn: "Class",
      offset: 1276,
      size: 1,
      unit: "u8",
      max: 0x13,
      confidence: "probable",
      tooltip:
        "Beruf / Klasse. Bestimmt Starttalente, erlaubte Waffen und Magietyp. Neue Berufe erfordern später ein eigenes Datenmodell.",
      evidence: {
        kind: "suspected",
        summary: "1 Byte je Charakter ab 1276, Enum 00–13 aus der Cheat-Tabelle.",
        source: I2_SRC,
        nextTest: I2_NEXT,
      },
    }),
    raceId: field({
      id: "raceId",
      label: "Rasse",
      labelEn: "Race",
      offset: 1281,
      size: 1,
      unit: "u8",
      min: 1,
      max: 5,
      confidence: "probable",
      tooltip:
        "Rasse. Beeinflusst Attribute und verfügbare Körpergrafiken. Offset für Attributsboni der Rasse: unbekannt (vermutlich statische Tabelle, nicht im Save).",
      evidence: {
        kind: "suspected",
        summary: "1 Byte je Charakter ab 1281, Enum 01–05.",
        source: I2_SRC,
        nextTest: I2_NEXT,
      },
    }),
    level: field({
      id: "level",
      label: "Stufe",
      labelEn: "Level",
      offset: 1291,
      size: 1,
      unit: "u8",
      confidence: "probable",
      tooltip: "Charakterstufe. Ishar 1: Zauber werden nicht automatisch mit Level gelernt.",
      evidence: {
        kind: "suspected",
        summary: "1 Byte je Charakter ab 1291.",
        source: I2_SRC,
        nextTest: I2_NEXT,
      },
    }),
    strength: field({
      id: "strength",
      label: "Kraft",
      labelEn: "Strength",
      offset: 1296,
      size: 1,
      unit: "u8",
      max: 0x7f,
      confidence: "probable",
      tooltip:
        "Stärke. Vermutet: Schaden, Tragekapazität, möglicherweise bestimmte Waffen. In Ishar 1 trainierbar.",
      evidence: {
        kind: "suspected",
        summary: "1 Byte je Charakter ab 1296.",
        source: I2_SRC,
        nextTest: I2_NEXT,
      },
    }),
    constitution: field({
      id: "constitution",
      label: "Verfassung",
      labelEn: "Constitution",
      offset: 1301,
      size: 1,
      unit: "u8",
      max: 0x7f,
      confidence: "probable",
      tooltip: "Konstitution. Vermutet: Vitalität, Gift-/Krankheitstoleranz. In Ishar 1 trainierbar.",
      evidence: {
        kind: "suspected",
        summary: "1 Byte je Charakter ab 1301.",
        source: I2_SRC,
        nextTest: I2_NEXT,
      },
    }),
    wisdom: field({
      id: "wisdom",
      label: "Weisheit",
      labelEn: "Wisdom",
      offset: 1306,
      size: 1,
      unit: "u8",
      max: 0x7f,
      confidence: "probable",
      tooltip: "Weisheit. Vermutet: klerikale Magie. In Ishar 1 trainierbar.",
      evidence: {
        kind: "suspected",
        summary: "1 Byte je Charakter ab 1306.",
        source: I2_SRC,
        nextTest: I2_NEXT,
      },
    }),
    intelligence: field({
      id: "intelligence",
      label: "Intelligenz",
      labelEn: "Intelligence",
      offset: 1311,
      size: 1,
      unit: "u8",
      max: 0x7f,
      confidence: "probable",
      tooltip: "Intelligenz. Vermutet: Magierzauber, Lernkosten. In Ishar 1 trainierbar.",
      evidence: {
        kind: "suspected",
        summary: "1 Byte je Charakter ab 1311.",
        source: I2_SRC,
        nextTest: I2_NEXT,
      },
    }),
    agility: field({
      id: "agility",
      label: "Beweglichkeit",
      labelEn: "Agility",
      offset: 1316,
      size: 1,
      unit: "u8",
      max: 0x7f,
      confidence: "probable",
      tooltip:
        "Geschicklichkeit. Vermutet: Trefferchance, Schlösser, Fernkampf. In Ishar 1 trainierbar.",
      evidence: {
        kind: "suspected",
        summary: "1 Byte je Charakter ab 1316.",
        source: I2_SRC,
        nextTest: I2_NEXT,
      },
    }),
    psychic: field({
      id: "psychic",
      label: "Geistig",
      labelEn: "Psychic / spell points",
      offset: 1321,
      size: 1,
      unit: "u8",
      max: 0x64,
      confidence: "probable",
      tooltip: "Geistige Kraft / Magiepunkte. Cheat-Tabelle nennt Maximum 0x64 (100).",
      evidence: {
        kind: "suspected",
        summary: "1 Byte je Charakter ab 1321, max 0x64 laut Tabelle.",
        source: I2_SRC,
        nextTest: I2_NEXT,
      },
    }),
    physical: field({
      id: "physical",
      label: "Körperlich",
      labelEn: "Physical / stamina",
      offset: 1326,
      size: 1,
      unit: "u8",
      max: 0x64,
      confidence: "probable",
      tooltip: "Körperliche Ausdauer. Rast und Nahrung. Maximum 0x64 laut Tabelle.",
      evidence: {
        kind: "suspected",
        summary: "1 Byte je Charakter ab 1326.",
        source: I2_SRC,
        nextTest: I2_NEXT,
      },
    }),
    armorClass: field({
      id: "armorClass",
      label: "Rüstungsklasse",
      labelEn: "Armor class",
      offset: 1336,
      size: 1,
      unit: "u8",
      confidence: "possible",
      tooltip: "Rüstungsklasse. Tabelle: höher = besser. Ob abgeleitet oder gespeichert, unklar.",
      evidence: {
        kind: "suspected",
        summary: "1 Byte je Charakter ab 1336.",
        source: I2_SRC,
        nextTest: "Rüstung an-/ablegen, speichern, Offset prüfen.",
      },
    }),
    skillOneHand: field({
      id: "skillOneHand",
      label: "Waffen einhändig",
      labelEn: "One-handed arms",
      offset: 7546,
      size: 1,
      unit: "u8",
      max: 0x64,
      confidence: "probable",
      tooltip: "Talent Einhänder. Basiswert Beruf + Attribute: Formel noch unbekannt.",
      evidence: {
        kind: "suspected",
        summary: "1 Byte je Charakter ab 7546.",
        source: I2_SRC,
        nextTest: I2_NEXT,
      },
    }),
    skillTwoHand: field({
      id: "skillTwoHand",
      label: "Waffen zweihändig",
      labelEn: "Two-handed arms",
      offset: 7551,
      size: 1,
      unit: "u8",
      max: 0x64,
      confidence: "probable",
      tooltip: "Talent Zweihandwaffen.",
      evidence: {
        kind: "suspected",
        summary: "1 Byte je Charakter ab 7551.",
        source: I2_SRC,
        nextTest: I2_NEXT,
      },
    }),
    skillThrow: field({
      id: "skillThrow",
      label: "Wurfwaffen",
      labelEn: "Throwing",
      offset: 7556,
      size: 1,
      unit: "u8",
      max: 0x64,
      confidence: "probable",
      tooltip: "Talent Wurfwaffen.",
      evidence: {
        kind: "suspected",
        summary: "1 Byte je Charakter ab 7556.",
        source: I2_SRC,
        nextTest: I2_NEXT,
      },
    }),
    skillShoot: field({
      id: "skillShoot",
      label: "Schießen",
      labelEn: "Shooting",
      offset: 7561,
      size: 1,
      unit: "u8",
      max: 0x64,
      confidence: "possible",
      tooltip:
        "Talent Schießen. Tabelle schreibt 7561–7566 (6 Bytes) — vermutlich Tippfehler, wir behandeln 5 Bytes.",
      evidence: {
        kind: "suspected",
        summary: "Tabelle 7561–7566; intern als 5-Byte-Array modelliert.",
        source: I2_SRC,
        nextTest: I2_NEXT,
      },
    }),
    skillLock: field({
      id: "skillLock",
      label: "Schlösser knacken",
      labelEn: "Lockpicking",
      offset: 7566,
      size: 1,
      unit: "u8",
      max: 0x64,
      confidence: "probable",
      tooltip: "Schlösser öffnen. Vermutet abhängig von Beweglichkeit.",
      evidence: {
        kind: "suspected",
        summary: "1 Byte je Charakter ab 7566.",
        source: I2_SRC,
        nextTest: I2_NEXT,
      },
    }),
    skillFirstAid: field({
      id: "skillFirstAid",
      label: "Erste Hilfe",
      labelEn: "First aid",
      offset: 7571,
      size: 1,
      unit: "u8",
      max: 0x64,
      confidence: "probable",
      tooltip: "Heilungstalent. Ishar-Party heilt über Rast, Zauber und dieses Talent.",
      evidence: {
        kind: "suspected",
        summary: "1 Byte je Charakter ab 7571.",
        source: I2_SRC,
        nextTest: I2_NEXT,
      },
    }),
    skillPerception: field({
      id: "skillPerception",
      label: "Wahrnehmung",
      labelEn: "Perception",
      offset: 7729,
      size: 1,
      unit: "u8",
      max: 0x64,
      confidence: "probable",
      tooltip: "Wahrnehmung. Fallen, geheime Türen, Hinterhalte.",
      evidence: {
        kind: "suspected",
        summary: "1 Byte je Charakter ab 7729.",
        source: I2_SRC,
        nextTest: I2_NEXT,
      },
    }),
  },
  inventory: {
    base: 1036,
    stride: 30,
    slotBytes: 2,
    backpack: 9,
    hands: 2,
    armor: 1,
    helm: 1,
    layout: [6, 7, 8, 3, 4, 5, 0, 1, 2],
    confidence: "probable",
    evidence: {
      kind: "suspected",
      summary:
        "9 Rucksackslots 2 Bytes, dann Hand1/Hand2/Rüstung/Helm. Raster 3 6 9 / 2 5 8 / 1 4 7. Stride 30 Bytes je Charakter.",
      source: I2_SRC + " / GOG-Forum IshadNha",
      nextTest: "Item aufnehmen, speichern, Item-ID im Inventarblock suchen.",
    },
  },
};

const I1_SRC =
  "GAME01.SAV DEBUG-Cheat (directx.pl): e 02D5/02DF/02E9/03E2/03E7/03EC/03F1/03F6/03FB/03FF/0400/0405. Unconfirmed.";

export const ISHAR1_SAVE: SaveMap = {
  id: "ishar1-sav-debug",
  game: "ishar1",
  title: "Ishar 1 Savegame (DOS, DEBUG cheat map)",
  partySize: 5,
  minLength: 0x0406 + 5,
  defaultEndian: "be",
  confidence: "possible",
  notes:
    "Nur die im DEBUG-Skript gepatchten Bytes. Namen, Inventar, Zauber, Rasse: unbekannt. 5-Byte-Abstand bei Attributen deutet auf dasselbe Array-of-5-Layout wie Ishar 2.",
  classes: ISHAR2_CLASSES,
  races: ISHAR2_RACES,
  fields: {
    hp: field({
      id: "hp",
      label: "Vitalität",
      labelEn: "Vitality",
      offset: 0x02d5,
      size: 1,
      unit: "u8",
      confidence: "possible",
      tooltip: "DEBUG setzt 0x02D5 auf FF = 255 Vitalität. Größe 1 vs 2 Bytes unklar.",
      evidence: {
        kind: "suspected",
        summary: "Einzelnes Byte 0x02D5 in GAME01.SAV.",
        source: I1_SRC,
        nextTest: "Vor/nach Kampf speichern, Byte 0x02D5 prüfen. Nachbarbytes (2-Byte-HP?) mitprüfen.",
      },
    }),
    gold: field({
      id: "gold",
      label: "Gold",
      labelEn: "Gold",
      offset: 0x02df,
      size: 1,
      unit: "u8",
      confidence: "possible",
      tooltip: "DEBUG: 0x02DF = FF. Ishar 1 verlangt Gold zum Speichern.",
      evidence: {
        kind: "suspected",
        summary: "Byte 0x02DF.",
        source: I1_SRC,
        nextTest: "Gold ausgeben, speichern, Offset 0x02DF und Umgebung diffen.",
      },
    }),
    psychic: field({
      id: "psychic",
      label: "Geistig",
      labelEn: "Psychic",
      offset: 0x02e9,
      size: 1,
      unit: "u8",
      confidence: "possible",
      tooltip: "DEBUG: 0x02E9 = FF.",
      evidence: {
        kind: "suspected",
        summary: "Byte 0x02E9.",
        source: I1_SRC,
        nextTest: I2_NEXT,
      },
    }),
    level: field({
      id: "level",
      label: "Stufe",
      labelEn: "Level",
      offset: 0x03e2,
      size: 1,
      unit: "u8",
      confidence: "possible",
      tooltip: "DEBUG: 0x03E2 = 7F (Stufe 127/128). 5-Byte-Abstand zum nächsten Attribut.",
      evidence: {
        kind: "suspected",
        summary: "Byte 0x03E2, Stride 5 über die Party.",
        source: I1_SRC,
        nextTest: I2_NEXT,
      },
    }),
    strength: field({
      id: "strength",
      label: "Kraft",
      labelEn: "Strength",
      offset: 0x03e7,
      size: 1,
      unit: "u8",
      confidence: "possible",
      tooltip: "DEBUG: 0x03E7 = 7F.",
      evidence: {
        kind: "suspected",
        summary: "Byte 0x03E7.",
        source: I1_SRC,
        nextTest: I2_NEXT,
      },
    }),
    wisdom: field({
      id: "wisdom",
      label: "Weisheit",
      labelEn: "Wisdom",
      offset: 0x03ec,
      size: 1,
      unit: "u8",
      confidence: "possible",
      tooltip: "DEBUG: 0x03EC = 7F.",
      evidence: {
        kind: "suspected",
        summary: "Byte 0x03EC.",
        source: I1_SRC,
        nextTest: I2_NEXT,
      },
    }),
    constitution: field({
      id: "constitution",
      label: "Verfassung",
      labelEn: "Constitution",
      offset: 0x03f1,
      size: 1,
      unit: "u8",
      confidence: "possible",
      tooltip: "DEBUG: 0x03F1 = 7F.",
      evidence: {
        kind: "suspected",
        summary: "Byte 0x03F1.",
        source: I1_SRC,
        nextTest: I2_NEXT,
      },
    }),
    agility: field({
      id: "agility",
      label: "Beweglichkeit",
      labelEn: "Agility",
      offset: 0x03f6,
      size: 1,
      unit: "u8",
      confidence: "possible",
      tooltip: "DEBUG: 0x03F6 = 33.",
      evidence: {
        kind: "suspected",
        summary: "Byte 0x03F6.",
        source: I1_SRC,
        nextTest: I2_NEXT,
      },
    }),
    intelligence: field({
      id: "intelligence",
      label: "Intelligenz",
      labelEn: "Intelligence",
      offset: 0x03fb,
      size: 1,
      unit: "u8",
      confidence: "possible",
      tooltip: "DEBUG: 0x03FB = 33.",
      evidence: {
        kind: "suspected",
        summary: "Byte 0x03FB.",
        source: I1_SRC,
        nextTest: I2_NEXT,
      },
    }),
    physical: field({
      id: "physical",
      label: "Körperlich",
      labelEn: "Physical",
      offset: 0x0400,
      size: 1,
      unit: "u8",
      confidence: "possible",
      tooltip: "DEBUG: 0x0400 = 77. 0x03FF wurde als 'skills' beschrieben — unbelegt.",
      evidence: {
        kind: "suspected",
        summary: "Byte 0x0400.",
        source: I1_SRC,
        nextTest: I2_NEXT,
      },
    }),
  },
};

export const SAVE_MAPS = {
  ishar1: ISHAR1_SAVE,
  ishar2: ISHAR2_SAVE,
};

export const KNOWN_ITEM_IDS: Record<number, string> = {
  0xffa7: "Chaos-Helm",
  0xffb9: "Chaos-Rüstung",
  0xff9b: "Chaos-Axt +25",
  0xffcf: "20 Pfeile",
};

export function className(map: SaveMap, id: number): string {
  return map.classes.find((c) => c.id === id)?.name ?? `Beruf ${id}`;
}

export function raceName(map: SaveMap, id: number): string {
  return map.races.find((r) => r.id === id)?.name ?? (id ? `Rasse ${id}` : "—");
}

export function itemName(id: number): string {
  if (id === 0) return "leer";
  return KNOWN_ITEM_IDS[id] ?? `Item ${id.toString(16).toUpperCase().padStart(4, "0")}`;
}
